title: Python bytes - Gore boodschappen
hero_image: images/banner.png
description: Schrijf een weerzinwekkende receptenkaart met behulp van variabelen, f-tekenreeksen en wiskunde
meta_title: Leer programmeren met Gore boodschappen | Python Bytes
meta_description: Leer hoe je Python f-tekenreeksen en variabelen kunt gebruiken om een walgelijk recept voor een vreemd restaurant af te drukken.
version: 1
listed: true
copyedit: false
last_tested: "2025-04-14"
steps:
  - title: step_1
  - title: step_2
    completion:
      - engaged
  - title: step_3
  - title: step_4
  - title: step_5
    completion:
      - internal
      - external
