title: Python bytes - Gross groceries
hero_image: images/banner.png
description: Write a revolting recipe card using variables, f-strings, and maths
meta_title: Learn to code with Gross Groceries | Python Bytes
meta_description: Learn how to use Python f-strings and variables to print a disgusting recipe for an odd restaurant.
version: 1
listed: false
copyedit: false
last_tested: "2025-04-14"
steps:
  - title: step_1
  - title: step_2
    completion:
      - engaged
  - title: step_3
  - title: step_4
  - title: step_5
    completion:
      - internal
      - external
