title: "Spicy Strings 🌶️🧪"
hero_image: images/banner.png
description: Build a space-themed play with Python f-strings and emojis.
meta_title: Python coding projects for kids and teens | Spicy Strings
meta_description: Use Python f-strings, variables, and emoji to script a silly space café scene and fix a robot's maths mistake!
version: 2
listed: false
copyedit: false
last_tested: "2025-04-04"
steps:
  - title: step_1
  - title: step_2
    completion:
      - engaged
  - title: step_3
  - title: step_4
  - title: step_5
  - title: step_6
    completion:
      - internal
      - external
